"""create academico tables

Revision ID: df7421c05691
Revises: 
Create Date: 2026-10-03 14:15:36.232413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df7421c05691'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo_formacao', sa.String(), nullable=False),
    sa.Column('modalidade', sa.String(), nullable=False),
    sa.Column('nivel_academico', sa.String(), nullable=False),
    sa.Column('carga_horaria_total', sa.Integer(), nullable=False),
    sa.Column('campus', sa.String(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('documentacao', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('departamento', sa.String(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('periodo_curricular', sa.Integer(), nullable=True),
    sa.Column('ementa', sa.String(), nullable=True),
    sa.Column('bibliografia', sa.String(), nullable=True),
    sa.Column('pre_requisitos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disciplinas')
    op.drop_table('cursos')
    # ### end Alembic commands ###
