"""remove admin model and add is_admin to usuario

Revision ID: a958bdfe4a9f
Revises: 81fad79aa97e
Create Date: 2026-10-02 18:19:53.259338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a958bdfe4a9f'
down_revision: Union[str, Sequence[str], None] = '81fad79aa97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # We should move tipo to is_admin
    op.add_column('usuarios', sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))
    
    op.execute("UPDATE usuarios SET is_admin = 1 WHERE tipo = 'ADMIN'")
    
    op.drop_table('admins')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('is_admin')

    op.create_table('admins',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('matricula_id', sa.VARCHAR(), nullable=False),
    sa.Column('setor', sa.VARCHAR(), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
