"""remove academico tables

Revision ID: b4decd5fc102
Revises: f4f8bd83c8a1
Create Date: 2026-10-02 17:07:54.098400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4decd5fc102'
down_revision: Union[str, Sequence[str], None] = 'f4f8bd83c8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    op.drop_table('professores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professores',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('matricula_id', sa.VARCHAR(), nullable=False),
    sa.Column('departamento_id', sa.VARCHAR(), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('matricula_id', sa.VARCHAR(), nullable=False),
    sa.Column('curso_id', sa.VARCHAR(), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
